[2025-09-19T10:07:11.820+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-09-19T10:07:12.082+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt_intermediate.intermediate.locations.test manual__2025-09-19T10:00:34.117962+00:00 [queued]>
[2025-09-19T10:07:12.096+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt_intermediate.intermediate.locations.test manual__2025-09-19T10:00:34.117962+00:00 [queued]>
[2025-09-19T10:07:12.097+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-09-19T10:07:12.118+0000] {taskinstance.py:2330} INFO - Executing <Task(DbtTestVirtualenvOperator): intermediate.locations.test> on 2025-09-19 10:00:34.117962+00:00
[2025-09-19T10:07:12.125+0000] {standard_task_runner.py:64} INFO - Started process 2037 to run task
[2025-09-19T10:07:12.129+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dbt_intermediate', 'intermediate.locations.test', 'manual__2025-09-19T10:00:34.117962+00:00', '--job-id', '548', '--raw', '--subdir', 'DAGS_FOLDER/dbt_intermediate.py', '--cfg-path', '/tmp/tmpky_gvh7p']
[2025-09-19T10:07:12.134+0000] {standard_task_runner.py:91} INFO - Job 548: Subtask intermediate.locations.test
[2025-09-19T10:07:12.553+0000] {task_command.py:426} INFO - Running <TaskInstance: dbt_intermediate.intermediate.locations.test manual__2025-09-19T10:00:34.117962+00:00 [running]> on host e95bde6b8d07
[2025-09-19T10:07:12.915+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dbt_intermediate' AIRFLOW_CTX_TASK_ID='intermediate.locations.test' AIRFLOW_CTX_EXECUTION_DATE='2025-09-19T10:00:34.117962+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-19T10:00:34.117962+00:00'
[2025-09-19T10:07:12.917+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-09-19T10:07:12.933+0000] {baseoperator.py:400} WARNING - DbtTestVirtualenvOperator.execute cannot be called outside TaskInstance!
[2025-09-19T10:07:12.934+0000] {virtualenv.py:120} INFO - Checking if the virtualenv lock /tmp/cosmos_venv_ecom_intermediate/cosmos_virtualenv.lock exists
[2025-09-19T10:07:12.934+0000] {virtualenv.py:178} INFO - Checking for running process with PID 1822
[2025-09-19T10:07:12.935+0000] {virtualenv.py:181} INFO - Process 1822 running: True and has the lock /tmp/cosmos_venv_ecom_intermediate/cosmos_virtualenv.lock.
[2025-09-19T10:07:12.935+0000] {virtualenv.py:122} INFO - Waiting for virtualenv lock to be released
[2025-09-19T10:07:13.937+0000] {virtualenv.py:178} INFO - Checking for running process with PID 1611
[2025-09-19T10:07:13.938+0000] {virtualenv.py:181} INFO - Process 1611 running: True and has the lock /tmp/cosmos_venv_ecom_intermediate/cosmos_virtualenv.lock.
[2025-09-19T10:07:13.939+0000] {virtualenv.py:122} INFO - Waiting for virtualenv lock to be released
[2025-09-19T10:07:14.941+0000] {virtualenv.py:178} INFO - Checking for running process with PID 1611
[2025-09-19T10:07:14.942+0000] {virtualenv.py:181} INFO - Process 1611 running: True and has the lock /tmp/cosmos_venv_ecom_intermediate/cosmos_virtualenv.lock.
[2025-09-19T10:07:14.942+0000] {virtualenv.py:122} INFO - Waiting for virtualenv lock to be released
[2025-09-19T10:07:15.944+0000] {virtualenv.py:178} INFO - Checking for running process with PID 1611
[2025-09-19T10:07:15.945+0000] {virtualenv.py:181} INFO - Process 1611 running: True and has the lock /tmp/cosmos_venv_ecom_intermediate/cosmos_virtualenv.lock.
[2025-09-19T10:07:15.946+0000] {virtualenv.py:122} INFO - Waiting for virtualenv lock to be released
[2025-09-19T10:07:16.947+0000] {virtualenv.py:178} INFO - Checking for running process with PID 1611
[2025-09-19T10:07:16.948+0000] {virtualenv.py:181} INFO - Process 1611 running: True and has the lock /tmp/cosmos_venv_ecom_intermediate/cosmos_virtualenv.lock.
[2025-09-19T10:07:16.949+0000] {virtualenv.py:122} INFO - Waiting for virtualenv lock to be released
[2025-09-19T10:07:17.951+0000] {virtualenv.py:178} INFO - Checking for running process with PID 1611
[2025-09-19T10:07:17.952+0000] {virtualenv.py:181} INFO - Process 1611 running: True and has the lock /tmp/cosmos_venv_ecom_intermediate/cosmos_virtualenv.lock.
[2025-09-19T10:07:17.952+0000] {virtualenv.py:122} INFO - Waiting for virtualenv lock to be released
[2025-09-19T10:07:18.953+0000] {virtualenv.py:178} INFO - Checking for running process with PID 1611
[2025-09-19T10:07:18.954+0000] {virtualenv.py:181} INFO - Process 1611 running: True and has the lock /tmp/cosmos_venv_ecom_intermediate/cosmos_virtualenv.lock.
[2025-09-19T10:07:18.954+0000] {virtualenv.py:122} INFO - Waiting for virtualenv lock to be released
[2025-09-19T10:07:19.957+0000] {virtualenv.py:178} INFO - Checking for running process with PID 1611
[2025-09-19T10:07:19.958+0000] {virtualenv.py:181} INFO - Process 1611 running: True and has the lock /tmp/cosmos_venv_ecom_intermediate/cosmos_virtualenv.lock.
[2025-09-19T10:07:19.959+0000] {virtualenv.py:122} INFO - Waiting for virtualenv lock to be released
[2025-09-19T10:07:20.961+0000] {virtualenv.py:178} INFO - Checking for running process with PID 1611
[2025-09-19T10:07:20.962+0000] {virtualenv.py:181} INFO - Process 1611 running: True and has the lock /tmp/cosmos_venv_ecom_intermediate/cosmos_virtualenv.lock.
[2025-09-19T10:07:20.963+0000] {virtualenv.py:122} INFO - Waiting for virtualenv lock to be released
[2025-09-19T10:07:21.965+0000] {virtualenv.py:178} INFO - Checking for running process with PID 1611
[2025-09-19T10:07:21.966+0000] {virtualenv.py:181} INFO - Process 1611 running: True and has the lock /tmp/cosmos_venv_ecom_intermediate/cosmos_virtualenv.lock.
[2025-09-19T10:07:21.967+0000] {virtualenv.py:122} INFO - Waiting for virtualenv lock to be released
[2025-09-19T10:07:22.970+0000] {virtualenv.py:178} INFO - Checking for running process with PID 1611
[2025-09-19T10:07:22.970+0000] {virtualenv.py:181} INFO - Process 1611 running: True and has the lock /tmp/cosmos_venv_ecom_intermediate/cosmos_virtualenv.lock.
[2025-09-19T10:07:22.974+0000] {virtualenv.py:122} INFO - Waiting for virtualenv lock to be released
[2025-09-19T10:07:23.976+0000] {virtualenv.py:178} INFO - Checking for running process with PID 1611
[2025-09-19T10:07:23.985+0000] {virtualenv.py:181} INFO - Process 1611 running: True and has the lock /tmp/cosmos_venv_ecom_intermediate/cosmos_virtualenv.lock.
[2025-09-19T10:07:23.992+0000] {virtualenv.py:122} INFO - Waiting for virtualenv lock to be released
[2025-09-19T10:07:24.998+0000] {virtualenv.py:178} INFO - Checking for running process with PID 1611
[2025-09-19T10:07:24.999+0000] {virtualenv.py:181} INFO - Process 1611 running: True and has the lock /tmp/cosmos_venv_ecom_intermediate/cosmos_virtualenv.lock.
[2025-09-19T10:07:25.000+0000] {virtualenv.py:122} INFO - Waiting for virtualenv lock to be released
[2025-09-19T10:07:26.002+0000] {virtualenv.py:178} INFO - Checking for running process with PID 1611
[2025-09-19T10:07:26.003+0000] {virtualenv.py:181} INFO - Process 1611 running: True and has the lock /tmp/cosmos_venv_ecom_intermediate/cosmos_virtualenv.lock.
[2025-09-19T10:07:26.004+0000] {virtualenv.py:122} INFO - Waiting for virtualenv lock to be released
[2025-09-19T10:07:27.006+0000] {virtualenv.py:178} INFO - Checking for running process with PID 2123
[2025-09-19T10:07:27.007+0000] {virtualenv.py:181} INFO - Process 2123 running: True and has the lock /tmp/cosmos_venv_ecom_intermediate/cosmos_virtualenv.lock.
[2025-09-19T10:07:27.007+0000] {virtualenv.py:122} INFO - Waiting for virtualenv lock to be released
[2025-09-19T10:07:27.851+0000] {local_task_job_runner.py:313} WARNING - State of this instance has been externally set to None. Terminating instance.
[2025-09-19T10:07:27.852+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2025-09-19T10:07:27.855+0000] {process_utils.py:132} INFO - Sending 15 to group 2037. PIDs of all processes in the group: [2037]
[2025-09-19T10:07:27.855+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 2037
[2025-09-19T10:07:27.856+0000] {taskinstance.py:2611} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-09-19T10:07:27.856+0000] {virtualenv.py:131} INFO - Releasing virtualenv lock
[2025-09-19T10:07:27.857+0000] {virtualenv.py:210} WARNING - Lockfile owned by process of pid 2123, while operator has pid 2037
[2025-09-19T10:07:27.857+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-09-19T10:07:27.898+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/cosmos/operators/virtualenv.py", line 144, in execute
    output = super().execute(context)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/cosmos/operators/local.py", line 1089, in execute
    result = self.build_and_run_cmd(context=context, cmd_flags=self.add_cmd_flags())
  File "/home/airflow/.local/lib/python3.10/site-packages/cosmos/operators/local.py", line 853, in build_and_run_cmd
    result = self.run_command(
  File "/home/airflow/.local/lib/python3.10/site-packages/cosmos/operators/virtualenv.py", line 123, in run_command
    time.sleep(1)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 2613, in signal_handler
    raise AirflowTaskTerminated("Task received SIGTERM signal")
airflow.exceptions.AirflowTaskTerminated: Task received SIGTERM signal
[2025-09-19T10:07:27.902+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=dbt_intermediate, task_id=intermediate.locations.test, run_id=manual__2025-09-19T10:00:34.117962+00:00, execution_date=20250919T100034, start_date=20250919T100712, end_date=20250919T100727
[2025-09-19T10:07:27.925+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 548 for task intermediate.locations.test ((psycopg2.errors.ForeignKeyViolation) insert or update on table "task_fail" violates foreign key constraint "task_fail_ti_fkey"
DETAIL:  Key (dag_id, task_id, run_id, map_index)=(dbt_intermediate, intermediate.locations.test, manual__2025-09-19T10:00:34.117962+00:00, -1) is not present in table "task_instance".

[SQL: INSERT INTO task_fail (task_id, dag_id, run_id, map_index, start_date, end_date, duration) VALUES (%(task_id)s, %(dag_id)s, %(run_id)s, %(map_index)s, %(start_date)s, %(end_date)s, %(duration)s) RETURNING task_fail.id]
[parameters: {'task_id': 'intermediate.locations.test', 'dag_id': 'dbt_intermediate', 'run_id': 'manual__2025-09-19T10:00:34.117962+00:00', 'map_index': -1, 'start_date': datetime.datetime(2025, 9, 19, 10, 7, 12, 83629, tzinfo=Timezone('UTC')), 'end_date': datetime.datetime(2025, 9, 19, 10, 7, 27, 902150, tzinfo=Timezone('UTC')), 'duration': 15}]
(Background on this error at: https://sqlalche.me/e/14/gkpj); 2037)
[2025-09-19T10:07:27.948+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=2037, status='terminated', exitcode=1, started='10:07:12') (2037) terminated with exit code 1
