[2025-09-13T09:30:41.322+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-09-13T09:30:41.379+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt_intermediate.intermediate.categories_enriched.test manual__2025-09-13T09:28:37.455030+00:00 [queued]>
[2025-09-13T09:30:41.391+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt_intermediate.intermediate.categories_enriched.test manual__2025-09-13T09:28:37.455030+00:00 [queued]>
[2025-09-13T09:30:41.402+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-09-13T09:30:41.428+0000] {taskinstance.py:2330} INFO - Executing <Task(DbtTestVirtualenvOperator): intermediate.categories_enriched.test> on 2025-09-13 09:28:37.455030+00:00
[2025-09-13T09:30:41.436+0000] {standard_task_runner.py:64} INFO - Started process 4604 to run task
[2025-09-13T09:30:41.441+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dbt_intermediate', 'intermediate.categories_enriched.test', 'manual__2025-09-13T09:28:37.455030+00:00', '--job-id', '162', '--raw', '--subdir', 'DAGS_FOLDER/dbt_intermediate.py', '--cfg-path', '/tmp/tmp0557iz_x']
[2025-09-13T09:30:41.445+0000] {standard_task_runner.py:91} INFO - Job 162: Subtask intermediate.categories_enriched.test
[2025-09-13T09:30:41.609+0000] {task_command.py:426} INFO - Running <TaskInstance: dbt_intermediate.intermediate.categories_enriched.test manual__2025-09-13T09:28:37.455030+00:00 [running]> on host e95bde6b8d07
[2025-09-13T09:30:41.869+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dbt_intermediate' AIRFLOW_CTX_TASK_ID='intermediate.categories_enriched.test' AIRFLOW_CTX_EXECUTION_DATE='2025-09-13T09:28:37.455030+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-13T09:28:37.455030+00:00'
[2025-09-13T09:30:41.873+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-09-13T09:30:41.889+0000] {baseoperator.py:400} WARNING - DbtTestVirtualenvOperator.execute cannot be called outside TaskInstance!
[2025-09-13T09:30:41.890+0000] {virtualenv.py:120} INFO - Checking if the virtualenv lock /tmp/cosmos_venv_ecom_intermediate/cosmos_virtualenv.lock exists
[2025-09-13T09:30:41.890+0000] {virtualenv.py:178} INFO - Checking for running process with PID 4137
[2025-09-13T09:30:41.891+0000] {virtualenv.py:181} INFO - Process 4137 running: True and has the lock /tmp/cosmos_venv_ecom_intermediate/cosmos_virtualenv.lock.
[2025-09-13T09:30:41.891+0000] {virtualenv.py:122} INFO - Waiting for virtualenv lock to be released
[2025-09-13T09:30:42.893+0000] {virtualenv.py:178} INFO - Checking for running process with PID 4137
[2025-09-13T09:30:42.894+0000] {virtualenv.py:181} INFO - Process 4137 running: True and has the lock /tmp/cosmos_venv_ecom_intermediate/cosmos_virtualenv.lock.
[2025-09-13T09:30:42.894+0000] {virtualenv.py:122} INFO - Waiting for virtualenv lock to be released
[2025-09-13T09:30:43.896+0000] {virtualenv.py:178} INFO - Checking for running process with PID 4137
[2025-09-13T09:30:43.897+0000] {virtualenv.py:181} INFO - Process 4137 running: True and has the lock /tmp/cosmos_venv_ecom_intermediate/cosmos_virtualenv.lock.
[2025-09-13T09:30:43.898+0000] {virtualenv.py:122} INFO - Waiting for virtualenv lock to be released
[2025-09-13T09:30:44.899+0000] {virtualenv.py:178} INFO - Checking for running process with PID 4137
[2025-09-13T09:30:44.900+0000] {virtualenv.py:181} INFO - Process 4137 running: True and has the lock /tmp/cosmos_venv_ecom_intermediate/cosmos_virtualenv.lock.
[2025-09-13T09:30:44.901+0000] {virtualenv.py:122} INFO - Waiting for virtualenv lock to be released
[2025-09-13T09:30:45.903+0000] {virtualenv.py:131} INFO - Releasing virtualenv lock
[2025-09-13T09:30:45.905+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-09-13T09:30:45.915+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/cosmos/operators/virtualenv.py", line 121, in run_command
    while not self._is_lock_available() and self.max_retries_lock:
  File "/home/airflow/.local/lib/python3.10/site-packages/cosmos/operators/virtualenv.py", line 52, in wrapper
    return method(operator, *args)
  File "/home/airflow/.local/lib/python3.10/site-packages/cosmos/operators/virtualenv.py", line 177, in _is_lock_available
    pid = int(lf.read())
ValueError: invalid literal for int() with base 10: ''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/cosmos/operators/virtualenv.py", line 144, in execute
    output = super().execute(context)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/cosmos/operators/local.py", line 1089, in execute
    result = self.build_and_run_cmd(context=context, cmd_flags=self.add_cmd_flags())
  File "/home/airflow/.local/lib/python3.10/site-packages/cosmos/operators/local.py", line 853, in build_and_run_cmd
    result = self.run_command(
  File "/home/airflow/.local/lib/python3.10/site-packages/cosmos/operators/virtualenv.py", line 132, in run_command
    self._release_venv_lock()
  File "/home/airflow/.local/lib/python3.10/site-packages/cosmos/operators/virtualenv.py", line 52, in wrapper
    return method(operator, *args)
  File "/home/airflow/.local/lib/python3.10/site-packages/cosmos/operators/virtualenv.py", line 205, in _release_venv_lock
    lock_file_pid = int(lf.read())
ValueError: invalid literal for int() with base 10: ''
[2025-09-13T09:30:45.989+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=dbt_intermediate, task_id=intermediate.categories_enriched.test, run_id=manual__2025-09-13T09:28:37.455030+00:00, execution_date=20250913T092837, start_date=20250913T093041, end_date=20250913T093045
[2025-09-13T09:30:46.047+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 162 for task intermediate.categories_enriched.test (invalid literal for int() with base 10: ''; 4604)
[2025-09-13T09:30:46.110+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2025-09-13T09:30:46.297+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-09-13T09:30:46.318+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
