[2025-09-12T15:16:05.722+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-09-12T15:16:05.790+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt_run_exec.dbt_run manual__2025-09-12T15:16:05.007540+00:00 [queued]>
[2025-09-12T15:16:05.802+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt_run_exec.dbt_run manual__2025-09-12T15:16:05.007540+00:00 [queued]>
[2025-09-12T15:16:05.813+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-09-12T15:16:05.831+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): dbt_run> on 2025-09-12 15:16:05.007540+00:00
[2025-09-12T15:16:05.836+0000] {standard_task_runner.py:64} INFO - Started process 916 to run task
[2025-09-12T15:16:05.841+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dbt_run_exec', 'dbt_run', 'manual__2025-09-12T15:16:05.007540+00:00', '--job-id', '84', '--raw', '--subdir', 'DAGS_FOLDER/dbt_staging.py', '--cfg-path', '/tmp/tmp3rz23kye']
[2025-09-12T15:16:05.844+0000] {standard_task_runner.py:91} INFO - Job 84: Subtask dbt_run
[2025-09-12T15:16:06.005+0000] {task_command.py:426} INFO - Running <TaskInstance: dbt_run_exec.dbt_run manual__2025-09-12T15:16:05.007540+00:00 [running]> on host e95bde6b8d07
[2025-09-12T15:16:06.224+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dbt_run_exec' AIRFLOW_CTX_TASK_ID='dbt_run' AIRFLOW_CTX_EXECUTION_DATE='2025-09-12T15:16:05.007540+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-12T15:16:05.007540+00:00'
[2025-09-12T15:16:06.225+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-09-12T15:16:06.238+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-09-12T15:16:06.239+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '\n    cd /opt/***/dags/dbt/ecom_staging &&     dbt run --select models/ecom_staging/ --profiles-dir /opt/***/dags/dbt\n    ']
[2025-09-12T15:16:06.247+0000] {subprocess.py:86} INFO - Output:
[2025-09-12T15:16:08.389+0000] {subprocess.py:93} INFO - [0m15:16:08  Encountered an error:
[2025-09-12T15:16:08.390+0000] {subprocess.py:93} INFO - [Errno 13] Permission denied: '/opt/***/dags/dbt/ecom_staging/logs/dbt.log'
[2025-09-12T15:16:08.404+0000] {subprocess.py:93} INFO - [0m15:16:08  Traceback (most recent call last):
[2025-09-12T15:16:08.409+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.10/site-packages/dbt/cli/requires.py", line 178, in wrapper
[2025-09-12T15:16:08.409+0000] {subprocess.py:93} INFO -     result, success = func(*args, **kwargs)
[2025-09-12T15:16:08.410+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.10/site-packages/dbt/cli/requires.py", line 101, in wrapper
[2025-09-12T15:16:08.411+0000] {subprocess.py:93} INFO -     setup_event_logger(flags=flags, callbacks=callbacks)
[2025-09-12T15:16:08.411+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.10/site-packages/dbt/events/logging.py", line 100, in setup_event_logger
[2025-09-12T15:16:08.412+0000] {subprocess.py:93} INFO -     add_logger_to_manager(
[2025-09-12T15:16:08.412+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.10/site-packages/dbt_common/events/event_manager_client.py", line 15, in add_logger_to_manager
[2025-09-12T15:16:08.413+0000] {subprocess.py:93} INFO -     _EVENT_MANAGER.add_logger(logger)
[2025-09-12T15:16:08.414+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.10/site-packages/dbt_common/events/event_manager.py", line 88, in add_logger
[2025-09-12T15:16:08.415+0000] {subprocess.py:93} INFO -     _JsonLogger(config) if config.line_format == LineFormat.Json else _TextLogger(config)
[2025-09-12T15:16:08.416+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.10/site-packages/dbt_common/events/logger.py", line 147, in __init__
[2025-09-12T15:16:08.417+0000] {subprocess.py:93} INFO -     super().__init__(config)
[2025-09-12T15:16:08.418+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.10/site-packages/dbt_common/events/logger.py", line 107, in __init__
[2025-09-12T15:16:08.418+0000] {subprocess.py:93} INFO -     file_handler = RotatingFileHandler(
[2025-09-12T15:16:08.419+0000] {subprocess.py:93} INFO -   File "/usr/local/lib/python3.10/logging/handlers.py", line 155, in __init__
[2025-09-12T15:16:08.420+0000] {subprocess.py:93} INFO -     BaseRotatingHandler.__init__(self, filename, mode, encoding=encoding,
[2025-09-12T15:16:08.420+0000] {subprocess.py:93} INFO -   File "/usr/local/lib/python3.10/logging/handlers.py", line 58, in __init__
[2025-09-12T15:16:08.421+0000] {subprocess.py:93} INFO -     logging.FileHandler.__init__(self, filename, mode=mode,
[2025-09-12T15:16:08.421+0000] {subprocess.py:93} INFO -   File "/usr/local/lib/python3.10/logging/__init__.py", line 1169, in __init__
[2025-09-12T15:16:08.422+0000] {subprocess.py:93} INFO -     StreamHandler.__init__(self, self._open())
[2025-09-12T15:16:08.422+0000] {subprocess.py:93} INFO -   File "/usr/local/lib/python3.10/logging/__init__.py", line 1201, in _open
[2025-09-12T15:16:08.423+0000] {subprocess.py:93} INFO -     return open_func(self.baseFilename, self.mode,
[2025-09-12T15:16:08.424+0000] {subprocess.py:93} INFO - PermissionError: [Errno 13] Permission denied: '/opt/***/dags/dbt/ecom_staging/logs/dbt.log'
[2025-09-12T15:16:08.424+0000] {subprocess.py:93} INFO - 
[2025-09-12T15:16:08.670+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2025-09-12T15:16:08.671+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-09-12T15:16:08.712+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2025-09-12T15:16:08.716+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=dbt_run_exec, task_id=dbt_run, run_id=manual__2025-09-12T15:16:05.007540+00:00, execution_date=20250912T151605, start_date=20250912T151605, end_date=20250912T151608
[2025-09-12T15:16:08.753+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 84 for task dbt_run (Bash command failed. The command returned a non-zero exit code 2.; 916)
[2025-09-12T15:16:08.787+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2025-09-12T15:16:08.835+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-09-12T15:16:08.848+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
