[2025-09-19T10:16:47.604+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-09-19T10:16:47.902+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt_intermediate.intermediate.subcategories_enriched.test manual__2025-09-19T10:14:55.158074+00:00 [queued]>
[2025-09-19T10:16:47.916+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt_intermediate.intermediate.subcategories_enriched.test manual__2025-09-19T10:14:55.158074+00:00 [queued]>
[2025-09-19T10:16:47.917+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-09-19T10:16:47.933+0000] {taskinstance.py:2330} INFO - Executing <Task(DbtTestVirtualenvOperator): intermediate.subcategories_enriched.test> on 2025-09-19 10:14:55.158074+00:00
[2025-09-19T10:16:47.941+0000] {standard_task_runner.py:64} INFO - Started process 3070 to run task
[2025-09-19T10:16:47.945+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dbt_intermediate', 'intermediate.subcategories_enriched.test', 'manual__2025-09-19T10:14:55.158074+00:00', '--job-id', '570', '--raw', '--subdir', 'DAGS_FOLDER/dbt_intermediate.py', '--cfg-path', '/tmp/tmpiqeaatub']
[2025-09-19T10:16:47.948+0000] {standard_task_runner.py:91} INFO - Job 570: Subtask intermediate.subcategories_enriched.test
[2025-09-19T10:16:48.109+0000] {task_command.py:426} INFO - Running <TaskInstance: dbt_intermediate.intermediate.subcategories_enriched.test manual__2025-09-19T10:14:55.158074+00:00 [running]> on host e95bde6b8d07
[2025-09-19T10:16:48.376+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dbt_intermediate' AIRFLOW_CTX_TASK_ID='intermediate.subcategories_enriched.test' AIRFLOW_CTX_EXECUTION_DATE='2025-09-19T10:14:55.158074+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-19T10:14:55.158074+00:00'
[2025-09-19T10:16:48.378+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-09-19T10:16:48.394+0000] {baseoperator.py:400} WARNING - DbtTestVirtualenvOperator.execute cannot be called outside TaskInstance!
[2025-09-19T10:16:48.396+0000] {virtualenv.py:120} INFO - Checking if the virtualenv lock /opt/***/cosmos_venvs/ecom_intermediate/cosmos_virtualenv.lock exists
[2025-09-19T10:16:48.397+0000] {virtualenv.py:178} INFO - Checking for running process with PID 2922
[2025-09-19T10:16:48.398+0000] {virtualenv.py:181} INFO - Process 2922 running: True and has the lock /opt/***/cosmos_venvs/ecom_intermediate/cosmos_virtualenv.lock.
[2025-09-19T10:16:48.398+0000] {virtualenv.py:122} INFO - Waiting for virtualenv lock to be released
[2025-09-19T10:16:49.400+0000] {virtualenv.py:178} INFO - Checking for running process with PID 2922
[2025-09-19T10:16:49.401+0000] {virtualenv.py:181} INFO - Process 2922 running: True and has the lock /opt/***/cosmos_venvs/ecom_intermediate/cosmos_virtualenv.lock.
[2025-09-19T10:16:49.402+0000] {virtualenv.py:122} INFO - Waiting for virtualenv lock to be released
[2025-09-19T10:16:50.404+0000] {virtualenv.py:178} INFO - Checking for running process with PID 2922
[2025-09-19T10:16:50.405+0000] {virtualenv.py:181} INFO - Process 2922 running: True and has the lock /opt/***/cosmos_venvs/ecom_intermediate/cosmos_virtualenv.lock.
[2025-09-19T10:16:50.406+0000] {virtualenv.py:122} INFO - Waiting for virtualenv lock to be released
[2025-09-19T10:16:51.408+0000] {virtualenv.py:178} INFO - Checking for running process with PID 2922
[2025-09-19T10:16:51.409+0000] {virtualenv.py:181} INFO - Process 2922 running: True and has the lock /opt/***/cosmos_venvs/ecom_intermediate/cosmos_virtualenv.lock.
[2025-09-19T10:16:51.410+0000] {virtualenv.py:122} INFO - Waiting for virtualenv lock to be released
[2025-09-19T10:16:52.412+0000] {virtualenv.py:178} INFO - Checking for running process with PID 2922
[2025-09-19T10:16:52.413+0000] {virtualenv.py:181} INFO - Process 2922 running: True and has the lock /opt/***/cosmos_venvs/ecom_intermediate/cosmos_virtualenv.lock.
[2025-09-19T10:16:52.414+0000] {virtualenv.py:122} INFO - Waiting for virtualenv lock to be released
[2025-09-19T10:16:53.416+0000] {virtualenv.py:178} INFO - Checking for running process with PID 2922
[2025-09-19T10:16:53.418+0000] {virtualenv.py:181} INFO - Process 2922 running: True and has the lock /opt/***/cosmos_venvs/ecom_intermediate/cosmos_virtualenv.lock.
[2025-09-19T10:16:53.419+0000] {virtualenv.py:122} INFO - Waiting for virtualenv lock to be released
[2025-09-19T10:16:54.421+0000] {virtualenv.py:178} INFO - Checking for running process with PID 2922
[2025-09-19T10:16:54.422+0000] {virtualenv.py:181} INFO - Process 2922 running: True and has the lock /opt/***/cosmos_venvs/ecom_intermediate/cosmos_virtualenv.lock.
[2025-09-19T10:16:54.423+0000] {virtualenv.py:122} INFO - Waiting for virtualenv lock to be released
[2025-09-19T10:16:55.424+0000] {virtualenv.py:178} INFO - Checking for running process with PID 2922
[2025-09-19T10:16:55.425+0000] {virtualenv.py:181} INFO - Process 2922 running: True and has the lock /opt/***/cosmos_venvs/ecom_intermediate/cosmos_virtualenv.lock.
[2025-09-19T10:16:55.426+0000] {virtualenv.py:122} INFO - Waiting for virtualenv lock to be released
[2025-09-19T10:16:56.427+0000] {virtualenv.py:178} INFO - Checking for running process with PID 2922
[2025-09-19T10:16:56.428+0000] {virtualenv.py:181} INFO - Process 2922 running: True and has the lock /opt/***/cosmos_venvs/ecom_intermediate/cosmos_virtualenv.lock.
[2025-09-19T10:16:56.429+0000] {virtualenv.py:122} INFO - Waiting for virtualenv lock to be released
[2025-09-19T10:16:57.430+0000] {virtualenv.py:178} INFO - Checking for running process with PID 2922
[2025-09-19T10:16:57.431+0000] {virtualenv.py:181} INFO - Process 2922 running: True and has the lock /opt/***/cosmos_venvs/ecom_intermediate/cosmos_virtualenv.lock.
[2025-09-19T10:16:57.432+0000] {virtualenv.py:122} INFO - Waiting for virtualenv lock to be released
[2025-09-19T10:16:58.433+0000] {virtualenv.py:178} INFO - Checking for running process with PID 2922
[2025-09-19T10:16:58.434+0000] {virtualenv.py:181} INFO - Process 2922 running: True and has the lock /opt/***/cosmos_venvs/ecom_intermediate/cosmos_virtualenv.lock.
[2025-09-19T10:16:58.434+0000] {virtualenv.py:122} INFO - Waiting for virtualenv lock to be released
[2025-09-19T10:16:59.436+0000] {virtualenv.py:178} INFO - Checking for running process with PID 2922
[2025-09-19T10:16:59.437+0000] {virtualenv.py:181} INFO - Process 2922 running: True and has the lock /opt/***/cosmos_venvs/ecom_intermediate/cosmos_virtualenv.lock.
[2025-09-19T10:16:59.438+0000] {virtualenv.py:122} INFO - Waiting for virtualenv lock to be released
[2025-09-19T10:17:00.440+0000] {virtualenv.py:126} INFO - Acquiring the virtualenv lock
[2025-09-19T10:17:00.440+0000] {virtualenv.py:195} INFO - Acquiring lock at /opt/***/cosmos_venvs/ecom_intermediate/cosmos_virtualenv.lock with pid 3070
[2025-09-19T10:17:00.441+0000] {virtualenv.py:153} INFO - Creating or updating the virtualenv at `/opt/***/cosmos_venvs/ecom_intermediate
[2025-09-19T10:17:00.442+0000] {process_utils.py:183} INFO - Executing cmd: /home/***/.local/bin/python -m virtualenv /opt/***/cosmos_venvs/ecom_intermediate --python=python3
[2025-09-19T10:17:00.443+0000] {process_utils.py:187} INFO - Output:
[2025-09-19T10:17:02.402+0000] {process_utils.py:191} INFO - RuntimeError: failed to build image pip because:
[2025-09-19T10:17:02.406+0000] {process_utils.py:191} INFO - Traceback (most recent call last):
[2025-09-19T10:17:02.407+0000] {process_utils.py:191} INFO -   File "/home/***/.local/lib/python3.10/site-packages/virtualenv/seed/embed/via_app_data/via_app_data.py", line 57, in _install
[2025-09-19T10:17:02.414+0000] {process_utils.py:191} INFO -     installer.install(creator.interpreter.version_info)
[2025-09-19T10:17:02.415+0000] {process_utils.py:191} INFO -   File "/home/***/.local/lib/python3.10/site-packages/virtualenv/seed/embed/via_app_data/pip_install/base.py", line 37, in install
[2025-09-19T10:17:02.416+0000] {process_utils.py:191} INFO -     self._sync(filename, into)
[2025-09-19T10:17:02.417+0000] {process_utils.py:191} INFO -   File "/home/***/.local/lib/python3.10/site-packages/virtualenv/seed/embed/via_app_data/pip_install/copy.py", line 13, in _sync
[2025-09-19T10:17:02.418+0000] {process_utils.py:191} INFO -     copy(src, dst)
[2025-09-19T10:17:02.419+0000] {process_utils.py:191} INFO -   File "/home/***/.local/lib/python3.10/site-packages/virtualenv/util/path/_sync.py", line 41, in copy
[2025-09-19T10:17:02.419+0000] {process_utils.py:191} INFO -     method(str(src), str(dest))
[2025-09-19T10:17:02.420+0000] {process_utils.py:191} INFO -   File "/home/***/.local/lib/python3.10/site-packages/virtualenv/util/path/_sync.py", line 52, in copytree
[2025-09-19T10:17:02.421+0000] {process_utils.py:191} INFO -     shutil.copy(src_f, dest_f)
[2025-09-19T10:17:02.422+0000] {process_utils.py:191} INFO -   File "/usr/local/lib/python3.10/shutil.py", line 418, in copy
[2025-09-19T10:17:02.422+0000] {process_utils.py:191} INFO -     copymode(src, dst, follow_symlinks=follow_symlinks)
[2025-09-19T10:17:02.423+0000] {process_utils.py:191} INFO -   File "/usr/local/lib/python3.10/shutil.py", line 307, in copymode
[2025-09-19T10:17:02.423+0000] {process_utils.py:191} INFO -     chmod_func(dst, stat.S_IMODE(st.st_mode))
[2025-09-19T10:17:02.424+0000] {process_utils.py:191} INFO - FileNotFoundError: [Errno 2] No such file or directory: '/opt/***/cosmos_venvs/ecom_intermediate/lib/python3.10/site-packages/pip-25.2.dist-info/licenses/src/pip/_vendor/distlib/LICENSE.txt'
[2025-09-19T10:17:02.424+0000] {process_utils.py:191} INFO - 
[2025-09-19T10:17:02.519+0000] {virtualenv.py:131} INFO - Releasing virtualenv lock
[2025-09-19T10:17:02.520+0000] {virtualenv.py:210} WARNING - Lockfile owned by process of pid 2683, while operator has pid 3070
[2025-09-19T10:17:02.520+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-09-19T10:17:02.521+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/cosmos/operators/virtualenv.py", line 144, in execute
    output = super().execute(context)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/cosmos/operators/local.py", line 1089, in execute
    result = self.build_and_run_cmd(context=context, cmd_flags=self.add_cmd_flags())
  File "/home/airflow/.local/lib/python3.10/site-packages/cosmos/operators/local.py", line 853, in build_and_run_cmd
    result = self.run_command(
  File "/home/airflow/.local/lib/python3.10/site-packages/cosmos/operators/virtualenv.py", line 128, in run_command
    self._py_bin = self._prepare_virtualenv()
  File "/home/airflow/.local/lib/python3.10/site-packages/cosmos/operators/virtualenv.py", line 154, in _prepare_virtualenv
    py_bin = prepare_virtualenv(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/python_virtualenv.py", line 105, in prepare_virtualenv
    execute_in_subprocess(virtualenv_cmd)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/process_utils.py", line 172, in execute_in_subprocess
    execute_in_subprocess_with_kwargs(cmd, cwd=cwd)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/process_utils.py", line 195, in execute_in_subprocess_with_kwargs
    raise subprocess.CalledProcessError(exit_code, cmd)
subprocess.CalledProcessError: Command '['/home/airflow/.local/bin/python', '-m', 'virtualenv', '/opt/airflow/cosmos_venvs/ecom_intermediate', '--python=python3']' returned non-zero exit status 1.
[2025-09-19T10:17:02.596+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=dbt_intermediate, task_id=intermediate.subcategories_enriched.test, run_id=manual__2025-09-19T10:14:55.158074+00:00, execution_date=20250919T101455, start_date=20250919T101647, end_date=20250919T101702
[2025-09-19T10:17:02.708+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 570 for task intermediate.subcategories_enriched.test (Command '['/home/airflow/.local/bin/python', '-m', 'virtualenv', '/opt/airflow/cosmos_venvs/ecom_intermediate', '--python=python3']' returned non-zero exit status 1.; 3070)
[2025-09-19T10:17:02.753+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2025-09-19T10:17:02.908+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-09-19T10:17:02.917+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
