[2025-09-12T15:18:07.920+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-09-12T15:18:07.978+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt_run_exec.dbt_run manual__2025-09-12T15:18:06.471287+00:00 [queued]>
[2025-09-12T15:18:07.987+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt_run_exec.dbt_run manual__2025-09-12T15:18:06.471287+00:00 [queued]>
[2025-09-12T15:18:07.998+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-09-12T15:18:08.015+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): dbt_run> on 2025-09-12 15:18:06.471287+00:00
[2025-09-12T15:18:08.020+0000] {standard_task_runner.py:64} INFO - Started process 960 to run task
[2025-09-12T15:18:08.024+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dbt_run_exec', 'dbt_run', 'manual__2025-09-12T15:18:06.471287+00:00', '--job-id', '85', '--raw', '--subdir', 'DAGS_FOLDER/dbt_staging.py', '--cfg-path', '/tmp/tmpcmax9n16']
[2025-09-12T15:18:08.027+0000] {standard_task_runner.py:91} INFO - Job 85: Subtask dbt_run
[2025-09-12T15:18:08.172+0000] {task_command.py:426} INFO - Running <TaskInstance: dbt_run_exec.dbt_run manual__2025-09-12T15:18:06.471287+00:00 [running]> on host e95bde6b8d07
[2025-09-12T15:18:08.396+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dbt_run_exec' AIRFLOW_CTX_TASK_ID='dbt_run' AIRFLOW_CTX_EXECUTION_DATE='2025-09-12T15:18:06.471287+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-12T15:18:06.471287+00:00'
[2025-09-12T15:18:08.397+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-09-12T15:18:08.408+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-09-12T15:18:08.409+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '\n    cd /opt/***/dags/dbt/ecom_staging &&     dbt run --select models/ecom_staging/ --profiles-dir /opt/***/dags/dbt\n    ']
[2025-09-12T15:18:08.417+0000] {subprocess.py:86} INFO - Output:
[2025-09-12T15:18:10.610+0000] {subprocess.py:93} INFO - [0m15:18:10  Encountered an error:
[2025-09-12T15:18:10.610+0000] {subprocess.py:93} INFO - [Errno 13] Permission denied: '/opt/***/dags/dbt/ecom_staging/logs/dbt.log'
[2025-09-12T15:18:10.611+0000] {subprocess.py:93} INFO - [0m15:18:10  Traceback (most recent call last):
[2025-09-12T15:18:10.611+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.10/site-packages/dbt/cli/requires.py", line 178, in wrapper
[2025-09-12T15:18:10.612+0000] {subprocess.py:93} INFO -     result, success = func(*args, **kwargs)
[2025-09-12T15:18:10.612+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.10/site-packages/dbt/cli/requires.py", line 101, in wrapper
[2025-09-12T15:18:10.613+0000] {subprocess.py:93} INFO -     setup_event_logger(flags=flags, callbacks=callbacks)
[2025-09-12T15:18:10.613+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.10/site-packages/dbt/events/logging.py", line 100, in setup_event_logger
[2025-09-12T15:18:10.613+0000] {subprocess.py:93} INFO -     add_logger_to_manager(
[2025-09-12T15:18:10.614+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.10/site-packages/dbt_common/events/event_manager_client.py", line 15, in add_logger_to_manager
[2025-09-12T15:18:10.614+0000] {subprocess.py:93} INFO -     _EVENT_MANAGER.add_logger(logger)
[2025-09-12T15:18:10.614+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.10/site-packages/dbt_common/events/event_manager.py", line 88, in add_logger
[2025-09-12T15:18:10.614+0000] {subprocess.py:93} INFO -     _JsonLogger(config) if config.line_format == LineFormat.Json else _TextLogger(config)
[2025-09-12T15:18:10.615+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.10/site-packages/dbt_common/events/logger.py", line 147, in __init__
[2025-09-12T15:18:10.615+0000] {subprocess.py:93} INFO -     super().__init__(config)
[2025-09-12T15:18:10.615+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.10/site-packages/dbt_common/events/logger.py", line 107, in __init__
[2025-09-12T15:18:10.616+0000] {subprocess.py:93} INFO -     file_handler = RotatingFileHandler(
[2025-09-12T15:18:10.616+0000] {subprocess.py:93} INFO -   File "/usr/local/lib/python3.10/logging/handlers.py", line 155, in __init__
[2025-09-12T15:18:10.616+0000] {subprocess.py:93} INFO -     BaseRotatingHandler.__init__(self, filename, mode, encoding=encoding,
[2025-09-12T15:18:10.616+0000] {subprocess.py:93} INFO -   File "/usr/local/lib/python3.10/logging/handlers.py", line 58, in __init__
[2025-09-12T15:18:10.617+0000] {subprocess.py:93} INFO -     logging.FileHandler.__init__(self, filename, mode=mode,
[2025-09-12T15:18:10.617+0000] {subprocess.py:93} INFO -   File "/usr/local/lib/python3.10/logging/__init__.py", line 1169, in __init__
[2025-09-12T15:18:10.617+0000] {subprocess.py:93} INFO -     StreamHandler.__init__(self, self._open())
[2025-09-12T15:18:10.617+0000] {subprocess.py:93} INFO -   File "/usr/local/lib/python3.10/logging/__init__.py", line 1201, in _open
[2025-09-12T15:18:10.618+0000] {subprocess.py:93} INFO -     return open_func(self.baseFilename, self.mode,
[2025-09-12T15:18:10.618+0000] {subprocess.py:93} INFO - PermissionError: [Errno 13] Permission denied: '/opt/***/dags/dbt/ecom_staging/logs/dbt.log'
[2025-09-12T15:18:10.618+0000] {subprocess.py:93} INFO - 
[2025-09-12T15:18:10.835+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2025-09-12T15:18:10.837+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-09-12T15:18:10.878+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2025-09-12T15:18:10.883+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=dbt_run_exec, task_id=dbt_run, run_id=manual__2025-09-12T15:18:06.471287+00:00, execution_date=20250912T151806, start_date=20250912T151807, end_date=20250912T151810
[2025-09-12T15:18:10.923+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 85 for task dbt_run (Bash command failed. The command returned a non-zero exit code 2.; 960)
[2025-09-12T15:18:10.967+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2025-09-12T15:18:11.014+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-09-12T15:18:11.021+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
