[2025-09-12T15:30:44.990+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-09-12T15:30:45.049+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt_run_exec.dbt_run manual__2025-09-12T15:30:43.965641+00:00 [queued]>
[2025-09-12T15:30:45.058+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt_run_exec.dbt_run manual__2025-09-12T15:30:43.965641+00:00 [queued]>
[2025-09-12T15:30:45.069+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-09-12T15:30:45.085+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): dbt_run> on 2025-09-12 15:30:43.965641+00:00
[2025-09-12T15:30:45.089+0000] {standard_task_runner.py:64} INFO - Started process 1262 to run task
[2025-09-12T15:30:45.092+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dbt_run_exec', 'dbt_run', 'manual__2025-09-12T15:30:43.965641+00:00', '--job-id', '88', '--raw', '--subdir', 'DAGS_FOLDER/dbt_staging.py', '--cfg-path', '/tmp/tmpc7z4dy4_']
[2025-09-12T15:30:45.095+0000] {standard_task_runner.py:91} INFO - Job 88: Subtask dbt_run
[2025-09-12T15:30:45.232+0000] {task_command.py:426} INFO - Running <TaskInstance: dbt_run_exec.dbt_run manual__2025-09-12T15:30:43.965641+00:00 [running]> on host e95bde6b8d07
[2025-09-12T15:30:45.458+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dbt_run_exec' AIRFLOW_CTX_TASK_ID='dbt_run' AIRFLOW_CTX_EXECUTION_DATE='2025-09-12T15:30:43.965641+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-12T15:30:43.965641+00:00'
[2025-09-12T15:30:45.459+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-09-12T15:30:45.471+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-09-12T15:30:45.472+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '\n        cd /opt/***/dags/dbt/ecom_staging &&         dbt run --select models/ecom_staging/ --profiles-dir /opt/***/dags/dbt/ecom_staging\n        ']
[2025-09-12T15:30:45.479+0000] {subprocess.py:86} INFO - Output:
[2025-09-12T15:30:47.624+0000] {subprocess.py:93} INFO - [0m15:30:47  Encountered an error:
[2025-09-12T15:30:47.625+0000] {subprocess.py:93} INFO - [Errno 13] Permission denied: '/opt/***/dags/dbt/ecom_staging/logs/dbt.log'
[2025-09-12T15:30:47.625+0000] {subprocess.py:93} INFO - [0m15:30:47  Traceback (most recent call last):
[2025-09-12T15:30:47.626+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.10/site-packages/dbt/cli/requires.py", line 178, in wrapper
[2025-09-12T15:30:47.626+0000] {subprocess.py:93} INFO -     result, success = func(*args, **kwargs)
[2025-09-12T15:30:47.626+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.10/site-packages/dbt/cli/requires.py", line 101, in wrapper
[2025-09-12T15:30:47.627+0000] {subprocess.py:93} INFO -     setup_event_logger(flags=flags, callbacks=callbacks)
[2025-09-12T15:30:47.627+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.10/site-packages/dbt/events/logging.py", line 100, in setup_event_logger
[2025-09-12T15:30:47.627+0000] {subprocess.py:93} INFO -     add_logger_to_manager(
[2025-09-12T15:30:47.628+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.10/site-packages/dbt_common/events/event_manager_client.py", line 15, in add_logger_to_manager
[2025-09-12T15:30:47.628+0000] {subprocess.py:93} INFO -     _EVENT_MANAGER.add_logger(logger)
[2025-09-12T15:30:47.628+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.10/site-packages/dbt_common/events/event_manager.py", line 88, in add_logger
[2025-09-12T15:30:47.629+0000] {subprocess.py:93} INFO -     _JsonLogger(config) if config.line_format == LineFormat.Json else _TextLogger(config)
[2025-09-12T15:30:47.629+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.10/site-packages/dbt_common/events/logger.py", line 147, in __init__
[2025-09-12T15:30:47.631+0000] {subprocess.py:93} INFO -     super().__init__(config)
[2025-09-12T15:30:47.631+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.10/site-packages/dbt_common/events/logger.py", line 107, in __init__
[2025-09-12T15:30:47.632+0000] {subprocess.py:93} INFO -     file_handler = RotatingFileHandler(
[2025-09-12T15:30:47.632+0000] {subprocess.py:93} INFO -   File "/usr/local/lib/python3.10/logging/handlers.py", line 155, in __init__
[2025-09-12T15:30:47.633+0000] {subprocess.py:93} INFO -     BaseRotatingHandler.__init__(self, filename, mode, encoding=encoding,
[2025-09-12T15:30:47.633+0000] {subprocess.py:93} INFO -   File "/usr/local/lib/python3.10/logging/handlers.py", line 58, in __init__
[2025-09-12T15:30:47.633+0000] {subprocess.py:93} INFO -     logging.FileHandler.__init__(self, filename, mode=mode,
[2025-09-12T15:30:47.634+0000] {subprocess.py:93} INFO -   File "/usr/local/lib/python3.10/logging/__init__.py", line 1169, in __init__
[2025-09-12T15:30:47.634+0000] {subprocess.py:93} INFO -     StreamHandler.__init__(self, self._open())
[2025-09-12T15:30:47.634+0000] {subprocess.py:93} INFO -   File "/usr/local/lib/python3.10/logging/__init__.py", line 1201, in _open
[2025-09-12T15:30:47.635+0000] {subprocess.py:93} INFO -     return open_func(self.baseFilename, self.mode,
[2025-09-12T15:30:47.635+0000] {subprocess.py:93} INFO - PermissionError: [Errno 13] Permission denied: '/opt/***/dags/dbt/ecom_staging/logs/dbt.log'
[2025-09-12T15:30:47.635+0000] {subprocess.py:93} INFO - 
[2025-09-12T15:30:47.859+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2025-09-12T15:30:47.860+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-09-12T15:30:47.904+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2025-09-12T15:30:47.909+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=dbt_run_exec, task_id=dbt_run, run_id=manual__2025-09-12T15:30:43.965641+00:00, execution_date=20250912T153043, start_date=20250912T153045, end_date=20250912T153047
[2025-09-12T15:30:47.948+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 88 for task dbt_run (Bash command failed. The command returned a non-zero exit code 2.; 1262)
[2025-09-12T15:30:47.956+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2025-09-12T15:30:48.006+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-09-12T15:30:48.008+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
