[2025-09-12T15:01:28.110+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-09-12T15:01:28.183+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt_run_bash.dbt_run manual__2025-09-12T15:01:27.063755+00:00 [queued]>
[2025-09-12T15:01:28.195+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt_run_bash.dbt_run manual__2025-09-12T15:01:27.063755+00:00 [queued]>
[2025-09-12T15:01:28.206+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-09-12T15:01:28.222+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): dbt_run> on 2025-09-12 15:01:27.063755+00:00
[2025-09-12T15:01:28.227+0000] {standard_task_runner.py:64} INFO - Started process 549 to run task
[2025-09-12T15:01:28.231+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dbt_run_bash', 'dbt_run', 'manual__2025-09-12T15:01:27.063755+00:00', '--job-id', '79', '--raw', '--subdir', 'DAGS_FOLDER/dbt_staging.py', '--cfg-path', '/tmp/tmpb4ko9mq3']
[2025-09-12T15:01:28.235+0000] {standard_task_runner.py:91} INFO - Job 79: Subtask dbt_run
[2025-09-12T15:01:28.422+0000] {task_command.py:426} INFO - Running <TaskInstance: dbt_run_bash.dbt_run manual__2025-09-12T15:01:27.063755+00:00 [running]> on host e95bde6b8d07
[2025-09-12T15:01:28.754+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dbt_run_bash' AIRFLOW_CTX_TASK_ID='dbt_run' AIRFLOW_CTX_EXECUTION_DATE='2025-09-12T15:01:27.063755+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-12T15:01:27.063755+00:00'
[2025-09-12T15:01:28.755+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-09-12T15:01:28.792+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-09-12T15:01:28.793+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '\n        cd /opt/***/dags/dbt &&         dbt run --select ecom_staging/models/ecom_staging/\n        ']
[2025-09-12T15:01:28.804+0000] {subprocess.py:86} INFO - Output:
[2025-09-12T15:01:31.560+0000] {subprocess.py:93} INFO - [0m15:01:31  Running with dbt=1.10.11
[2025-09-12T15:01:31.564+0000] {subprocess.py:93} INFO - [0m15:01:31  Encountered an error:
[2025-09-12T15:01:31.564+0000] {subprocess.py:93} INFO - Runtime Error
[2025-09-12T15:01:31.565+0000] {subprocess.py:93} INFO -   No dbt_project.yml found at expected path /opt/***/dags/dbt/dbt_project.yml
[2025-09-12T15:01:31.565+0000] {subprocess.py:93} INFO -   Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
[2025-09-12T15:01:31.566+0000] {subprocess.py:93} INFO - 
[2025-09-12T15:01:33.797+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2025-09-12T15:01:33.799+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-09-12T15:01:33.842+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2025-09-12T15:01:33.859+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=dbt_run_bash, task_id=dbt_run, run_id=manual__2025-09-12T15:01:27.063755+00:00, execution_date=20250912T150127, start_date=20250912T150128, end_date=20250912T150133
[2025-09-12T15:01:33.918+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 79 for task dbt_run (Bash command failed. The command returned a non-zero exit code 2.; 549)
[2025-09-12T15:01:33.964+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2025-09-12T15:01:34.018+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-09-12T15:01:34.030+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
