[2025-09-12T16:34:25.810+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-09-12T16:34:25.929+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: update_income_aggregate.update_income_aggregate scheduled__2025-09-10T00:00:00+00:00 [queued]>
[2025-09-12T16:34:25.939+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: update_income_aggregate.update_income_aggregate scheduled__2025-09-10T00:00:00+00:00 [queued]>
[2025-09-12T16:34:25.942+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-09-12T16:34:25.966+0000] {taskinstance.py:2330} INFO - Executing <Task(ClickHouseOperator): update_income_aggregate> on 2025-09-10 00:00:00+00:00
[2025-09-12T16:34:25.972+0000] {standard_task_runner.py:64} INFO - Started process 2815 to run task
[2025-09-12T16:34:25.977+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'update_income_aggregate', 'update_income_aggregate', 'scheduled__2025-09-10T00:00:00+00:00', '--job-id', '90', '--raw', '--subdir', 'DAGS_FOLDER/dd.py', '--cfg-path', '/tmp/tmp3wwp5ael']
[2025-09-12T16:34:25.981+0000] {standard_task_runner.py:91} INFO - Job 90: Subtask update_income_aggregate
[2025-09-12T16:34:26.159+0000] {task_command.py:426} INFO - Running <TaskInstance: update_income_aggregate.update_income_aggregate scheduled__2025-09-10T00:00:00+00:00 [running]> on host e95bde6b8d07
[2025-09-12T16:34:26.446+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='update_income_aggregate' AIRFLOW_CTX_TASK_ID='update_income_aggregate' AIRFLOW_CTX_EXECUTION_DATE='2025-09-10T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-10T00:00:00+00:00'
[2025-09-12T16:34:26.447+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-09-12T16:34:26.513+0000] {base.py:84} INFO - Using connection ID 'ch_ecom_staging_conn' for task execution.
[2025-09-12T16:34:26.515+0000] {clickhouse.py:79} INFO - 
                Select * from stg_categories
            
[2025-09-12T16:34:26.518+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-09-12T16:34:26.519+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow_clickhouse_plugin/operators/clickhouse.py", line 83, in execute
    return self._hook_execute()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow_clickhouse_plugin/operators/clickhouse.py", line 69, in _hook_execute
    return hook.execute(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow_clickhouse_plugin/hooks/clickhouse.py", line 80, in execute
    last_result = conn.execute(
  File "/home/airflow/.local/lib/python3.10/site-packages/clickhouse_driver/client.py", line 370, in execute
    with self.disconnect_on_error(query, settings):
  File "/usr/local/lib/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "/home/airflow/.local/lib/python3.10/site-packages/clickhouse_driver/client.py", line 313, in disconnect_on_error
    self.establish_connection(settings)
  File "/home/airflow/.local/lib/python3.10/site-packages/clickhouse_driver/client.py", line 300, in establish_connection
    self.connection.force_connect()
  File "/home/airflow/.local/lib/python3.10/site-packages/clickhouse_driver/connection.py", line 258, in force_connect
    self.connect()
  File "/home/airflow/.local/lib/python3.10/site-packages/clickhouse_driver/connection.py", line 399, in connect
    return self._init_connection(host, port)
  File "/home/airflow/.local/lib/python3.10/site-packages/clickhouse_driver/connection.py", line 343, in _init_connection
    self.receive_hello()
  File "/home/airflow/.local/lib/python3.10/site-packages/clickhouse_driver/connection.py", line 534, in receive_hello
    raise errors.UnexpectedPacketFromServerError(message)
clickhouse_driver.errors.UnexpectedPacketFromServerError: Code: 102. Unexpected packet from server clickhouse:8123 (expected Hello or Exception, got Unknown packet)
[2025-09-12T16:34:26.566+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=update_income_aggregate, task_id=update_income_aggregate, run_id=scheduled__2025-09-10T00:00:00+00:00, execution_date=20250910T000000, start_date=20250912T163425, end_date=20250912T163426
[2025-09-12T16:34:26.585+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 90 for task update_income_aggregate (Code: 102. Unexpected packet from server clickhouse:8123 (expected Hello or Exception, got Unknown packet); 2815)
[2025-09-12T16:34:26.632+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2025-09-12T16:34:26.694+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-09-12T16:34:26.699+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
