[2025-09-12T15:28:07.367+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-09-12T15:28:07.427+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt_run_exec.dbt_run manual__2025-09-12T15:28:06.459145+00:00 [queued]>
[2025-09-12T15:28:07.436+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt_run_exec.dbt_run manual__2025-09-12T15:28:06.459145+00:00 [queued]>
[2025-09-12T15:28:07.445+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-09-12T15:28:07.471+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): dbt_run> on 2025-09-12 15:28:06.459145+00:00
[2025-09-12T15:28:07.476+0000] {standard_task_runner.py:64} INFO - Started process 1198 to run task
[2025-09-12T15:28:07.479+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dbt_run_exec', 'dbt_run', 'manual__2025-09-12T15:28:06.459145+00:00', '--job-id', '87', '--raw', '--subdir', 'DAGS_FOLDER/dbt_staging.py', '--cfg-path', '/tmp/tmpitpzpui7']
[2025-09-12T15:28:07.482+0000] {standard_task_runner.py:91} INFO - Job 87: Subtask dbt_run
[2025-09-12T15:28:07.647+0000] {task_command.py:426} INFO - Running <TaskInstance: dbt_run_exec.dbt_run manual__2025-09-12T15:28:06.459145+00:00 [running]> on host e95bde6b8d07
[2025-09-12T15:28:07.933+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dbt_run_exec' AIRFLOW_CTX_TASK_ID='dbt_run' AIRFLOW_CTX_EXECUTION_DATE='2025-09-12T15:28:06.459145+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-12T15:28:06.459145+00:00'
[2025-09-12T15:28:07.934+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-09-12T15:28:07.944+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-09-12T15:28:07.945+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '\n        cd /opt/***/dags/dbt/ecom_staging &&         dbt run --select models/ecom_staging/ --profiles-dir /opt/***/dags/dbt/ecom_staging\n        ']
[2025-09-12T15:28:07.954+0000] {subprocess.py:86} INFO - Output:
[2025-09-12T15:28:10.058+0000] {subprocess.py:93} INFO - [0m15:28:10  Encountered an error:
[2025-09-12T15:28:10.059+0000] {subprocess.py:93} INFO - [Errno 13] Permission denied: '/opt/***/dags/dbt/ecom_staging/logs/dbt.log'
[2025-09-12T15:28:10.059+0000] {subprocess.py:93} INFO - [0m15:28:10  Traceback (most recent call last):
[2025-09-12T15:28:10.060+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.10/site-packages/dbt/cli/requires.py", line 178, in wrapper
[2025-09-12T15:28:10.060+0000] {subprocess.py:93} INFO -     result, success = func(*args, **kwargs)
[2025-09-12T15:28:10.061+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.10/site-packages/dbt/cli/requires.py", line 101, in wrapper
[2025-09-12T15:28:10.061+0000] {subprocess.py:93} INFO -     setup_event_logger(flags=flags, callbacks=callbacks)
[2025-09-12T15:28:10.061+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.10/site-packages/dbt/events/logging.py", line 100, in setup_event_logger
[2025-09-12T15:28:10.062+0000] {subprocess.py:93} INFO -     add_logger_to_manager(
[2025-09-12T15:28:10.062+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.10/site-packages/dbt_common/events/event_manager_client.py", line 15, in add_logger_to_manager
[2025-09-12T15:28:10.062+0000] {subprocess.py:93} INFO -     _EVENT_MANAGER.add_logger(logger)
[2025-09-12T15:28:10.062+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.10/site-packages/dbt_common/events/event_manager.py", line 88, in add_logger
[2025-09-12T15:28:10.063+0000] {subprocess.py:93} INFO -     _JsonLogger(config) if config.line_format == LineFormat.Json else _TextLogger(config)
[2025-09-12T15:28:10.063+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.10/site-packages/dbt_common/events/logger.py", line 147, in __init__
[2025-09-12T15:28:10.063+0000] {subprocess.py:93} INFO -     super().__init__(config)
[2025-09-12T15:28:10.064+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.10/site-packages/dbt_common/events/logger.py", line 107, in __init__
[2025-09-12T15:28:10.064+0000] {subprocess.py:93} INFO -     file_handler = RotatingFileHandler(
[2025-09-12T15:28:10.065+0000] {subprocess.py:93} INFO -   File "/usr/local/lib/python3.10/logging/handlers.py", line 155, in __init__
[2025-09-12T15:28:10.065+0000] {subprocess.py:93} INFO -     BaseRotatingHandler.__init__(self, filename, mode, encoding=encoding,
[2025-09-12T15:28:10.066+0000] {subprocess.py:93} INFO -   File "/usr/local/lib/python3.10/logging/handlers.py", line 58, in __init__
[2025-09-12T15:28:10.066+0000] {subprocess.py:93} INFO -     logging.FileHandler.__init__(self, filename, mode=mode,
[2025-09-12T15:28:10.066+0000] {subprocess.py:93} INFO -   File "/usr/local/lib/python3.10/logging/__init__.py", line 1169, in __init__
[2025-09-12T15:28:10.067+0000] {subprocess.py:93} INFO -     StreamHandler.__init__(self, self._open())
[2025-09-12T15:28:10.067+0000] {subprocess.py:93} INFO -   File "/usr/local/lib/python3.10/logging/__init__.py", line 1201, in _open
[2025-09-12T15:28:10.067+0000] {subprocess.py:93} INFO -     return open_func(self.baseFilename, self.mode,
[2025-09-12T15:28:10.067+0000] {subprocess.py:93} INFO - PermissionError: [Errno 13] Permission denied: '/opt/***/dags/dbt/ecom_staging/logs/dbt.log'
[2025-09-12T15:28:10.068+0000] {subprocess.py:93} INFO - 
[2025-09-12T15:28:10.288+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2025-09-12T15:28:10.289+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-09-12T15:28:10.327+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2025-09-12T15:28:10.332+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=dbt_run_exec, task_id=dbt_run, run_id=manual__2025-09-12T15:28:06.459145+00:00, execution_date=20250912T152806, start_date=20250912T152807, end_date=20250912T152810
[2025-09-12T15:28:10.371+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 87 for task dbt_run (Bash command failed. The command returned a non-zero exit code 2.; 1198)
[2025-09-12T15:28:10.388+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2025-09-12T15:28:10.440+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-09-12T15:28:10.445+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
